version: '3'

services:
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: confdb
      POSTGRES_USER: confdb
      POSTGRES_PASSWORD: confdb
    ports:
     - "5432:5432"
    volumes:
      - "pgdataconf:/var/lib/postgresql/data"
      
volumes:
  pgdataconf: {}
